CREATE TABLE batch_job_execution_seq (
  ID bigint(20) NOT NULL,
  UNIQUE_KEY char(1) NOT NULL,
  UNIQUE KEY UNIQUE_KEY_UN (UNIQUE_KEY)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;


-- batch.batch_job_instance definition

CREATE TABLE batch_job_instance (
  JOB_INSTANCE_ID bigint(20) NOT NULL AUTO_INCREMENT,
  VERSION bigint(20) DEFAULT NULL,
  JOB_NAME varchar(100) NOT NULL,
  JOB_KEY varchar(32) NOT NULL,
  PRIMARY KEY (JOB_INSTANCE_ID),
  UNIQUE KEY JOB_INST_UN (JOB_NAME,JOB_KEY)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;


-- batch.batch_job_seq definition

CREATE TABLE batch_job_seq (
  ID bigint(20) NOT NULL,
  UNIQUE_KEY char(1) NOT NULL,
  UNIQUE KEY UNIQUE_KEY_UN (UNIQUE_KEY)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;


-- batch.batch_step_execution_seq definition

CREATE TABLE batch_step_execution_seq (
  ID bigint(20) NOT NULL,
  UNIQUE_KEY char(1) NOT NULL,
  UNIQUE KEY UNIQUE_KEY_UN (UNIQUE_KEY)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;


-- batch.customers definition

CREATE TABLE customers (
  id varchar(100) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;


-- batch.people definition

CREATE TABLE people (
  person_id bigint(20) NOT NULL,
  first_name varchar(20) DEFAULT NULL,
  last_name varchar(20) DEFAULT NULL,
  PRIMARY KEY (person_id)
) ENGINE=InnoDB AUTO_INCREMENT=214 DEFAULT CHARSET=latin1;


-- batch.batch_job_execution definition

CREATE TABLE batch_job_execution (
  JOB_EXECUTION_ID bigint(20) NOT NULL,
  VERSION bigint(20) DEFAULT NULL,
  JOB_INSTANCE_ID bigint(20) NOT NULL,
  CREATE_TIME datetime(6) NOT NULL,
  START_TIME datetime(6) DEFAULT NULL,
  END_TIME datetime(6) DEFAULT NULL,
  STATUS varchar(10) DEFAULT NULL,
  EXIT_CODE varchar(2500) DEFAULT NULL,
  EXIT_MESSAGE varchar(2500) DEFAULT NULL,
  LAST_UPDATED datetime(6) DEFAULT NULL,
  JOB_CONFIGURATION_LOCATION varchar(2500) DEFAULT NULL,
  PRIMARY KEY (JOB_EXECUTION_ID),
  KEY JOB_INST_EXEC_FK (JOB_INSTANCE_ID),
  CONSTRAINT JOB_INST_EXEC_FK FOREIGN KEY (JOB_INSTANCE_ID) REFERENCES batch_job_instance (JOB_INSTANCE_ID)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;


-- batch.batch_job_execution_context definition

CREATE TABLE batch_job_execution_context (
  JOB_EXECUTION_ID bigint(20) NOT NULL,
  SHORT_CONTEXT varchar(2500) NOT NULL,
  SERIALIZED_CONTEXT text,
  PRIMARY KEY (JOB_EXECUTION_ID),
  CONSTRAINT JOB_EXEC_CTX_FK FOREIGN KEY (JOB_EXECUTION_ID) REFERENCES batch_job_execution (JOB_EXECUTION_ID)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;


-- batch.batch_job_execution_params definition

CREATE TABLE batch_job_execution_params (
  JOB_EXECUTION_ID bigint(20) NOT NULL,
  TYPE_CD varchar(6) NOT NULL,
  KEY_NAME varchar(100) NOT NULL,
  STRING_VAL varchar(250) DEFAULT NULL,
  DATE_VAL datetime(6) DEFAULT NULL,
  LONG_VAL bigint(20) DEFAULT NULL,
  DOUBLE_VAL double DEFAULT NULL,
  IDENTIFYING char(1) NOT NULL,
  KEY JOB_EXEC_PARAMS_FK (JOB_EXECUTION_ID),
  CONSTRAINT JOB_EXEC_PARAMS_FK FOREIGN KEY (JOB_EXECUTION_ID) REFERENCES batch_job_execution (JOB_EXECUTION_ID)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;


-- batch.batch_step_execution definition

CREATE TABLE batch_step_execution (
  STEP_EXECUTION_ID bigint(20) NOT NULL,
  VERSION bigint(20) NOT NULL,
  STEP_NAME varchar(100) NOT NULL,
  JOB_EXECUTION_ID bigint(20) NOT NULL,
  START_TIME datetime(6) NOT NULL,
  END_TIME datetime(6) DEFAULT NULL,
  STATUS varchar(10) DEFAULT NULL,
  COMMIT_COUNT bigint(20) DEFAULT NULL,
  READ_COUNT bigint(20) DEFAULT NULL,
  FILTER_COUNT bigint(20) DEFAULT NULL,
  WRITE_COUNT bigint(20) DEFAULT NULL,
  READ_SKIP_COUNT bigint(20) DEFAULT NULL,
  WRITE_SKIP_COUNT bigint(20) DEFAULT NULL,
  PROCESS_SKIP_COUNT bigint(20) DEFAULT NULL,
  ROLLBACK_COUNT bigint(20) DEFAULT NULL,
  EXIT_CODE varchar(2500) DEFAULT NULL,
  EXIT_MESSAGE varchar(2500) DEFAULT NULL,
  LAST_UPDATED datetime(6) DEFAULT NULL,
  PRIMARY KEY (STEP_EXECUTION_ID),
  KEY JOB_EXEC_STEP_FK (JOB_EXECUTION_ID),
  CONSTRAINT JOB_EXEC_STEP_FK FOREIGN KEY (JOB_EXECUTION_ID) REFERENCES batch_job_execution (JOB_EXECUTION_ID)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;


-- batch.batch_step_execution_context definition

CREATE TABLE batch_step_execution_context (
  STEP_EXECUTION_ID bigint(20) NOT NULL,
  SHORT_CONTEXT varchar(2500) NOT NULL,
  SERIALIZED_CONTEXT text,
  PRIMARY KEY (STEP_EXECUTION_ID),
  CONSTRAINT STEP_EXEC_CTX_FK FOREIGN KEY (STEP_EXECUTION_ID) REFERENCES batch_step_execution (STEP_EXECUTION_ID)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;